import { ExerciseStep, StretchAction } from '@/types';

export const eyeExerciseSteps: ExerciseStep[] = [
  {
    id: '1',
    name: '远眺放松',
    description: '看向远处20秒，放松眼部肌肉',
    duration: 20,
    animationType: 'look-far',
  },
  {
    id: '2',
    name: '眼球转动',
    description: '顺时针转动眼球10圈，然后逆时针10圈',
    duration: 30,
    animationType: 'eye-roll',
  },
  {
    id: '3',
    name: '眨眼练习',
    description: '快速眨眼20次，保持眼部湿润',
    duration: 20,
    animationType: 'blink',
  },
  {
    id: '4',
    name: '热敷眼睛',
    description: '双手搓热后轻敷眼部，深呼吸放松',
    duration: 30,
    animationType: 'warm',
  },
  {
    id: '5',
    name: '穴位按摩',
    description: '轻按睛明穴、太阳穴各10秒',
    duration: 30,
    animationType: 'massage',
  },
  {
    id: '6',
    name: '远近聚焦',
    description: '交替看近处指尖和远处物体各5秒',
    duration: 30,
    animationType: 'focus',
  },
];

export const stretchActions: StretchAction[] = [
  {
    id: 'n1',
    name: '颈部左右转动',
    category: 'neck',
    description: '缓慢将头转向左侧，保持15秒，然后转向右侧',
    duration: 30,
    steps: ['坐直，肩膀放松', '慢慢将头转向左侧', '保持15秒，感受拉伸', '慢慢转回正中', '换右侧重复'],
  },
  {
    id: 'n2',
    name: '颈部侧倾拉伸',
    category: 'neck',
    description: '将头倾向一侧，耳朵靠近肩膀',
    duration: 30,
    steps: ['坐直，肩膀放松下垂', '慢慢将头倾向左侧', '感受右侧颈部拉伸', '保持15秒后换边'],
  },
  {
    id: 'n3',
    name: '颈部前后拉伸',
    category: 'neck',
    description: '点头和抬头拉伸颈部前后肌肉',
    duration: 30,
    steps: ['坐直，放松肩膀', '慢慢低头，下巴靠近胸口', '保持10秒', '慢慢抬头，看向天花板', '保持10秒'],
  },
  {
    id: 'n4',
    name: '颈部绕环',
    category: 'neck',
    description: '缓慢做颈部绕环运动',
    duration: 30,
    steps: ['坐直，肩膀放松', '顺时针缓慢绕环5圈', '逆时针缓慢绕环5圈', '动作要慢，避免头晕'],
  },
  {
    id: 's1',
    name: '肩部环绕',
    category: 'shoulder',
    description: '双肩向后环绕，放松肩颈肌肉',
    duration: 30,
    steps: ['坐直，双手自然下垂', '肩膀向后画大圆', '重复10次后换方向'],
  },
  {
    id: 's2',
    name: '耸肩放松',
    category: 'shoulder',
    description: '耸肩靠近耳朵，然后放松落下',
    duration: 30,
    steps: ['坐直，双臂放松', '用力耸肩，靠近耳朵', '保持5秒后突然放松', '重复10次'],
  },
  {
    id: 's3',
    name: '扩胸拉伸',
    category: 'shoulder',
    description: '双手在背后交握，拉伸胸部和肩部前侧',
    duration: 30,
    steps: ['坐直，双手在背后交握', '慢慢抬起手臂', '胸部向前挺，肩膀向后展', '保持20秒'],
  },
  {
    id: 's4',
    name: '肩颈拉伸',
    category: 'shoulder',
    description: '手臂横过胸前，用另一只手轻压',
    duration: 30,
    steps: ['左臂横过胸前', '右手轻压左臂靠近胸口', '感受左肩后部拉伸', '保持15秒后换边'],
  },
  {
    id: 'w1',
    name: '手腕转动',
    category: 'wrist',
    description: '顺时针和逆时针转动手腕',
    duration: 30,
    steps: ['双手握拳', '顺时针转动手腕10次', '逆时针转动手腕10次', '动作要充分'],
  },
  {
    id: 'w2',
    name: '手指伸展',
    category: 'wrist',
    description: '张开手指，然后握拳，反复练习',
    duration: 30,
    steps: ['双手放在身前', '用力张开手指，保持5秒', '用力握拳，保持5秒', '重复10次'],
  },
  {
    id: 'w3',
    name: '手腕上下拉伸',
    category: 'wrist',
    description: '手掌向上和向下拉伸手腕',
    duration: 30,
    steps: ['手臂伸直，手掌向上', '另一只手轻拉手指向身体', '保持15秒', '手掌向下，重复动作'],
  },
  {
    id: 'w4',
    name: '手腕左右拉伸',
    category: 'wrist',
    description: '向左右两侧拉伸手腕',
    duration: 30,
    steps: ['手臂伸直，掌心向外', '手指向左侧倾斜', '另一只手辅助拉伸', '保持15秒后换边'],
  },
  {
    id: 'w5',
    name: '手臂放松',
    category: 'wrist',
    description: '甩动手臂，放松整个手臂',
    duration: 30,
    steps: ['站立，双臂自然下垂', '轻轻甩动手臂', '前后左右各方向甩动', '放松手腕和手肘'],
  },
  {
    id: 'b1',
    name: '脊柱扭转',
    category: 'back',
    description: '坐姿扭转脊柱，拉伸背部肌肉',
    duration: 30,
    steps: ['坐直，双脚平放', '身体向左侧扭转', '右手扶住左膝', '保持15秒后换边'],
  },
  {
    id: 'b2',
    name: '猫牛式伸展',
    category: 'back',
    description: '模仿猫和牛的动作，活动脊柱',
    duration: 30,
    steps: ['双手双膝着地', '吸气时抬头塌腰（牛式）', '呼气时含胸拱背（猫式）', '重复5次'],
  },
  {
    id: 'b3',
    name: '腰部侧拉伸',
    category: 'back',
    description: '站立向两侧弯曲，拉伸腰部',
    duration: 30,
    steps: ['站立，双脚与肩同宽', '左臂向上伸直', '身体向右侧弯曲', '保持15秒后换边'],
  },
];

export const painAreaLabels: Record<string, string> = {
  neck: '颈部',
  shoulder: '肩部',
  back: '腰部',
  wrist: '手腕',
  eye: '眼睛',
};

export const screenDistanceLabels: Record<string, string> = {
  too_close: '太近（<40cm）',
  normal: '适中（50-70cm）',
  too_far: '太远（>80cm）',
};
